# Jekyll config for GitHub Pages
title: "Lộ trình học TypeScript cho người biết Python"
description: "41 chủ đề học TypeScript có cấu trúc, mỗi chủ đề 5 phút. Dành cho Python developers muốn học TypeScript hiệu quả"
url: "https://nguyenngocbinh.github.io"
baseurl: "/typescript-roadmap"
author: "Nguyen Ngoc Binh"
lang: "vi"

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima  # Comment out for custom theme

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Syntax highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false

# SEO settings
google_analytics: # Add your GA tracking ID here
google_site_verification: # Add your GSV code here

# Social media
twitter:
  username: # Add Twitter username
  card: summary_large_image

facebook:
  app_id: # Add Facebook App ID
  publisher: # Add Facebook Page URL

# Navigation
header_pages:
  - index.md
  - week-1.md
  - week-2.md
  - week-3.md
  - week-4.md
  - bonus.md

# Exclude files
exclude:
  - .github/
  - README.md
  - DEPLOYMENT.md
  - SETUP_COMPLETE.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Include files
include:
  - _pages
  - assets

# Collections
collections:
  weeks:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Nguyen Ngoc Binh"
  - scope:
      path: ""
      type: "weeks"  
    values:
      layout: "default"
      author: "Nguyen Ngoc Binh"

# Compression
sass:
  style: compressed

# Performance
incremental: true
livereload: true

# Pagination
paginate: 10
paginate_path: "/page:num/"
